export interface TwilioMessageInterface {
    ApiVersion?: string,
    SmsSid?: string,
    SmsStatus?: string,
    SmsMessageSid?: string,
    NumSegments?: string,
    ToState?: string,
    From?: string,
    MessageSid?: string,
    AccountSid?: string,
    ToCity?: string,
    FromCountry?: string,
    ToZip?: string,
    FromCity?: string,
    To?: string,
    FromZip?: string,
    ToCountry?: string,
    Body?: string,
    NumMedia?: string,
    FromState?: string,
}